CC = gcc

executable = test

target_dir = dist
lib_dir = lib
src_dir = src

libraries = $(wildcard $(lib_dir)/*.h)
sources = $(wildcard $(src_dir)/*.c)
libraries_name = 
sources_name = 

objects = $(target_dir)/

all: $(target_dir) test

test: 

$(libraries): 

$(target_dir):
	mkdir $(target_dir)
	
clean:
	rm -r $(target_dir)
